/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ObrigadaRouteImport } from './routes/obrigada'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SelecaoRouteImport } from './routes/selecao'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as VendasRouteImport } from './routes/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadaRoute = ObrigadaRouteImport.update({
  id: '/obrigada',
  path: '/obrigada',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecaoRoute = SelecaoRouteImport.update({
  id: '/selecao',
  path: '/selecao',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/obrigada': typeof ObrigadaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/selecao': typeof SelecaoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/obrigada': typeof ObrigadaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/selecao': typeof SelecaoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/obrigada': typeof ObrigadaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/selecao': typeof SelecaoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/obrigada'
    | '/politica-de-privacidade'
    | '/selecao'
    | '/termos-de-uso'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/obrigada'
    | '/politica-de-privacidade'
    | '/selecao'
    | '/termos-de-uso'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/landing'
    | '/obrigada'
    | '/politica-de-privacidade'
    | '/selecao'
    | '/termos-de-uso'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  ObrigadaRoute: typeof ObrigadaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SelecaoRoute: typeof SelecaoRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigada': {
      id: '/obrigada'
      path: '/obrigada'
      fullPath: '/obrigada'
      preLoaderRoute: typeof ObrigadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecao': {
      id: '/selecao'
      path: '/selecao'
      fullPath: '/selecao'
      preLoaderRoute: typeof SelecaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  ObrigadaRoute: ObrigadaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SelecaoRoute: SelecaoRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
